version: "3"
services:
  postgis:
    image: mdillon/postgis:10-alpine
    ports:
    - 5555:5432
  cliquebait:
    image: foamspace/cliquebait:latest
    environment:
      - "ACCOUNTS_TO_CREATE=18"
    command: /cliquebait/run.bash --nodiscover --maxpeers=0 --gcmode=archive --targetgaslimit=0x8000000
    ports:
    - 8545:8545
  redis:
    image: redis:alpine
    ports:
    - 6379:6379
  flyway:
    image: flyway/flyway:latest-alpine
    depends_on:
      - postgis
    volumes:
      - ./migrations:/flyway/sql/migrations
