resolver: lts-14.4

packages:
- "server"
- "common"
- "indexer"
extra-deps:
 - opaleye-0.6.7004.1
ghc-options:
    "$locals": -Wall -Werror -Wno-error=missing-import-lists -fwarn-unused-binds -fwarn-unused-imports -Wno-error=unused-imports -ddump-splices -ddump-to-file
