name:                common
version:             0.1.0.0
github:              "githubuser/common"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2019 Author name here"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/common#readme>

default-extensions:
  - LambdaCase
  - DeriveGeneric
  - OverloadedStrings
  - DataKinds
  - TypeFamilies
  - MultiParamTypeClasses
  - FlexibleInstances
  - RankNTypes
  - GeneralizedNewtypeDeriving
  - TypeApplications
  - TypeOperators
  - DefaultSignatures
  - ScopedTypeVariables
  - RecordWildCards
  - ConstraintKinds

dependencies:
- aeson
- aeson-casing
- base >= 4.7 && < 5
- bytestring
- errors
- exceptions
- http-client
- katip
- lens
- lens-aeson
- memory
- mtl
- opaleye
- postgresql-simple
- product-profunctors
- profunctors
- hedis
- scientific
- string-conversions
- swagger2
- text
- web3

library:
  source-dirs: src
